---
# Make sure relevant system and desktop support packages are installed.
- name: Ensure base system packages
  package:
    name: '{{item}}'
    state: latest
  loop:
    - apt-transport-https
    - arc-theme
    - command-not-found
    - curl
    - dnsutils
    - file-roller
    - firewalld
    - firewall-config
    - gdm3
    - git
    - git-extras
    - gnome-color-manager
    - gnome-core
    - gnome-tweaks
    - gnupg
    - hexedit
    - htop
    - libcanberra-gtk-module
    - libpam-tmpdir
    - network-manager
    - network-manager-gnome
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - openssh-client
    - openssh-server
    - openvpn
    - p7zip
    - papirus-icon-theme
    - traceroute
    - unzip
    - wget
    - whois
    - zip
    - zsh
  tags: [ packages ]
  become: yes

# Ensure relevant APT keys are present on the system to support extra repositories added later.
- name: Add apt keys needed for software install
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '{{item}}'
  loop:
    - '8ED17AF5D7E675EB3EE3BCE98AC3B29174885C03' # AdoptOpenJDK
    - '0A0FAB860D48560332EFB581B75442BBDE9E3B09' # Atom
    - '9DC858229FC7DD38854AE2D88D81803C0EBFCD88' # Docker
    - '7F92E05B31093BEF5A3C2D38FEEA9169307EA071' # Google Cloud SDK
    - '59FE0256827269DC81578F928B57C5C2836F4BEB' # Google Cloud SDK
    - '4CCA1EAF950CEE4AB83976DCA040830F7FAC5991' # Google-1
    - 'EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796' # Google-2
    - 'AEE35447B5D3E4A69860622702F762CA6730E6A7' # libkafe
    - 'C80E383C3DE9F082E01391A0366C67DE91CA5D5F' # Lynis
    - '20691EEC35216C63CAF66CE1656408E390CFB1F5' # MongoDB v4.4 rel
    - '9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280' # NodeSource
    - 'D4040146BE3972509FD57FC71F3045A5DF7587C3' # Skype
    - 'DB085A08CA13B8ACB917E0F6D938EC0D038651BD' # Slack
    - '8FD3D9A8D3800305A9FFF259D1742AD60D811D58' # Spotify
    - 'B9F8D658297AF3EFC18D5CDFA2F683C52980AECF' # Virtualbox
    - '72ECF46A56B4AD39C907BBB71646B01B86E50310' # Yarn
  become: yes
  tags: [ packages ]

# Setup extra repositories needed on the system. Mostly development, productivity etc.
- name: Setup extra repositories for software install
  apt_repository:
    filename: '{{item.file}}'
    repo: '{{item.repo}}'
    state: present
  loop:
    - { file: 'adoptopenjdk', repo: 'deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ansible_distribution_release}} main' }
    - { file: 'atom-editor', repo: 'deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main' }
    - { file: 'docker', repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable' }
    - { file: 'google-chrome', repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' }
    - { file: 'google-cloud-sdk', repo: 'deb https://packages.cloud.google.com/apt cloud-sdk main' }
    - { file: 'insomnia', repo: 'deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all' }
    - { file: 'libkafe', repo: 'deb https://dl.cloudsmith.io/public/kafe/libkafe/deb/ubuntu {{ansible_distribution_release}} main' }
    - { file: 'mongodb-4.4', repo: 'deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/4.4 universe' }
    - { file: 'nodejs', repo: 'deb https://deb.nodesource.com/node_12.x {{ansible_distribution_release}} main' }
    - { file: 'skype-stable', repo: 'deb [arch=amd64] https://repo.skype.com/deb stable main' }
    - { file: 'slack', repo: 'deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main' }
    - { file: 'spotify', repo: 'deb http://repository.spotify.com stable non-free' } # HTTP :(
    - { file: 'virtualbox', repo: 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib' }
    - { file: 'yarn', repo: 'deb https://dl.yarnpkg.com/debian/ stable main' }
  become: yes
  tags: [ packages ]

- name: Install workstation packages
  package:
    name: '{{item}}'
    state: latest
  loop:
    - adoptopenjdk-11-openj9
    - adoptopenjdk-11-openj9-jre
    - adoptopenjdk-8-openj9
    - adoptopenjdk-8-openj9-jre
    - atom
    - clang-7
    - clang-8
    - cloud-utils
    - cmake
    - cups
    - docker-ce
    - eiskaltdcpp
    - ffmpeg
    - filezilla
    - fzf
    - geary
    - gimp
    - google-chrome-stable
    - google-cloud-sdk
    - gparted
    - inkscape
    - insomnia
    - kafe-cli
    - libarchive-dev
    - libbz2-dev
    - libcurl4-gnutls-dev
    - libgit2-dev
    - libguestfs-tools
    - liblua5.3-dev
    - libreoffice-base
    - libreoffice-calc
    - libreoffice-gnome
    - libreoffice-impress
    - libreoffice-writer
    - libsqlite3-dev
    - libssh-dev
    - make
    - meld
    - memcached
    - mongodb-org-shell
    - mongodb-org-tools
    - nodejs
    - openvpn
    - python3
    - python3-pip
    - skypeforlinux
    - slack-desktop
    - spotify-client
    - sshpass
    - telegram-desktop
    - terminator
    - tmux
    - tmuxinator
    - transmission
    - uget
    - v4l2loopback-dkms
    - v4l2loopback-utils
    - valgrind
    - vinagre
    - virt-manager
    - virtualbox-6.1
    - vlc
    - yarn
  become: yes
  tags: [ packages ]

- name: Ensure system files
  copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    mode: '0644'
    owner: root
    group: root
  loop:
    - { src: menu-icon.svg, dest: /etc/menu-icon.svg } # Used by Arc Menu GNOME extension.
    - { src: wallpaper.png, dest: /etc/wallpaper.png } # System default wallpaper
    - { src: issue.net, dest: /etc/issue.net } # System banner - for network clients
  become: yes

# Ensure DCONF profile is present on the system. This deals with desktop customization and defaults.
- name: Configure DCONF
  file:
    path: /etc/dconf/profile
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: yes

- name: Copy dconf user profile config
  copy:
    src: dconf_profile_user
    dest: /etc/dconf/profile/user
    mode: '0644'
    owner: root
    group: root
  become: yes

- name: Create /etc/dconf/db/local.d
  file:
    path: /etc/dconf/db/local.d
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: yes

- name: Update dconf settings
  copy:
    src: dconf_settings.ini
    dest: /etc/dconf/db/local.d/00-global
    mode: '0644'
    owner: root
    group: root
  notify: [ Update dconf ]
  become: yes
# END

# Configure SSH server
- name: Copy sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: '0644'
    owner: root
    group: root
  notify: [ Restart sshd ]
  become: yes

- name: Install oh-my-zsh for root
  script:
    cmd: 'scripts/oh-my-zsh-setup.sh --unattended --keep-zshrc'
    creates: '/root/.oh-my-zsh'
  changed_when: false # ignore
  become: yes

- name: Install oh-my-zsh for self
  script:
    cmd: 'scripts/oh-my-zsh-setup.sh --unattended --keep-zshrc'
    chdir: '/home/{{host_username}}'
    creates: '/home/{{host_username}}/.oh-my-zsh'
  changed_when: false # ignore

- name: Install fonts
  copy:
    src: fonts/
    dest: /usr/local/share/fonts
  become: yes

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
  become: yes

- name: Update own user profile
  user:
    name: '{{host_username}}'
    shell: /bin/zsh
    groups: docker
    append: yes
    create_home: yes
    password: '*' # Initial password is none, account locked
    update_password: on_create # Do not reset password from ansible
  become: yes

- name: Update root user profile
  user:
    name: root
    shell: /bin/zsh
  become: yes

- name: Ensure home directory has correct permissions
  file:
    path: '/home/{{host_username}}/'
    state: directory
    mode: '0700'
    owner: '{{host_username}}'
    group: '{{host_username}}'
  become: yes

- name: Create ~/.ssh/
  file:
    path: '/home/{{host_username}}/.ssh'
    state: directory
    mode: '0700'
    owner: '{{host_username}}'
    group: '{{host_username}}'
  become: yes

- name: Create ~/.atom/
  file:
    path: '/home/{{host_username}}/.atom'
    state: directory
    mode: '0700'
    owner: '{{host_username}}'
    group: '{{host_username}}'
  become: yes

- name: Ensure personal dot files
  copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    mode: '0600'
    owner: '{{host_username}}'
    group: '{{host_username}}'
  loop:
    - { src: dots/zshrc.zsh, dest: '/home/{{host_username}}/.zshrc' }
    - { src: dots/tmux.conf, dest: '/home/{{host_username}}/.tmux.conf' }
    - { src: dots/editorconfig, dest: '/home/{{host_username}}/.editorconfig' }
    - { src: dots/wgetrc, dest: '/home/{{host_username}}/.wgetrc' }
    - { src: dots/gitignore, dest: '/home/{{host_username}}/.gitignore' }
    - { src: dots/curlrc, dest: '/home/{{host_username}}/.curlrc' }
    - { src: dots/.atom/config.cson, dest: '/home/{{host_username}}/.atom/config.cson' }
    - { src: dots/.atom/styles.less, dest: '/home/{{host_username}}/.atom/styles.less' }

- name: Ensure root dot files
  copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    mode: '0600'
    owner: root
    group: root
  loop:
    - { src: dots/zshrc.zsh, dest: '/root/.zshrc' }
    - { src: dots/editorconfig, dest: '/root/.editorconfig' }
    - { src: dots/wgetrc, dest: '/root/.wgetrc' }
    - { src: dots/curlrc, dest: '/root/.curlrc' }
  become: yes

- name: Ensure personal files (from templates)
  template:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    mode: '0600'
    owner: '{{host_username}}'
    group: '{{host_username}}'
  loop:
    - { src: dots/gitconfig, dest: '/home/{{host_username}}/.gitconfig' }
    - { src: dots/authorized_keys, dest: '/home/{{host_username}}/.ssh/authorized_keys' }

- name: Ensure default directories in home
  file:
    path: '{{item}}'
    state: directory
    mode: '0700'
    owner: '{{host_username}}'
    group: '{{host_username}}'
  loop:
    - '/home/{{host_username}}/dots'
    - '/home/{{host_username}}/CLionProjects'
    - '/home/{{host_username}}/IdeaProjects'
  become: yes

# Configure icons in Nautilus for some directories.
- name: Set home folder icons
  shell: 'gio set -t string {{item.dir}} metadata::custom-icon file://{{item.icon}}'
  changed_when: false # Really not that important...
  loop:
    - { dir: '/home/{{host_username}}/CLionProjects', icon: '/usr/share/icons/Papirus/64x64/places/folder-cyan-development.svg' }
    - { dir: '/home/{{host_username}}/IdeaProjects', icon: '/usr/share/icons/Papirus/64x64/places/folder-pink-development.svg' }
    - { dir: '/home/{{host_username}}/dots', icon: '/usr/share/icons/Papirus/64x64/places/folder-orange-development.svg' }

# Install python extra packages and ensure they are up to date.
- name: Ensure pip3 packages
  pip:
    name: '{{item}}'
    executable: pip3
    state: latest
  loop:
    - ansible # Yo dawg i herd you like Ansible so we put a Ansible in yo Ansible so you can automate while u automate
    - awscli
    - backupcpy
    - cloudsmith-cli
    - django
    - docker-compose
    - fetchfox
    - jupyterlab
    - notebook
    - pipenv
  become: yes

# Make sure system services we explicitly need are running and enabled.
- name: Enable and start system services
  service:
    name: '{{item}}'
    state: started
    enabled: yes
  loop:
    - gdm
    - memcached
    - firewalld
    - ssh
  become: yes

- name: Install Node global packages (yarn)
  yarn:
    name: '{{item}}'
    global: yes
    state: latest
    production: yes
  loop:
    - '@angular/cli'
    - '@vue/cli'
    - 'docusaurus-init'
    - 'nativescript'
    - 'svgo'
  changed_when: false # ignore
  become: yes

- name: Install composer globally
  script:
    cmd: 'scripts/composer-setup.sh'
    chdir: /tmp
    creates: /usr/local/bin/composer
  changed_when: false # ignore
  become: yes

- name: Install Symfony CLI globally
  script:
    cmd: 'scripts/symfony-setup.sh --install-dir=/usr/local/bin/'
    chdir: /tmp
    creates: /usr/local/bin/symfony
  changed_when: false # ignore
  become: yes

- name: Install pyenv for own user
  script:
    cmd: 'scripts/pyenv-setup.sh'
    chdir: '/home/{{host_username}}'
    creates: '/home/{{host_username}}/.pyenv'
  changed_when: false # ignore
