---
- name: Restart sshd
  service: name=sshd state=restarted
  become: true

- name: Update APT
  shell: apt update
  become: true

- name: Update dconf
  shell: dconf update
  become: true

- name: Update initramfs
  shell: update-initramfs -u
  become: true

- name: Install fetchfox stable
  shell: fetchfox stable
